// src/app/layout.js

import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import ClientThemeProvider from './components/ClientThemeProvider';
import "./globals.css";
import Head from 'next/head';



export const metadata = {
  title: "K2N TECH",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='dark'>
    <Head>
      <title>K2N</title>
      <meta name="description" content={metadata.description} />
      <meta name="keywords" content="k2n, tech, k2n tech, website, 9tonkla, maprang" />
      <meta property="og:title" content={metadata.title} />
      <meta property="og:description" content={metadata.description} />
      <meta property="og:type" content="website" />
      <meta property="og:url" content="https://www.example.com" />
    </Head>
      <body className='font-mitr bg-gradient-to-b from-blue-50 bg-white dark:bg-gray-100 to-white dark:from-slate-900'>
        <ClientThemeProvider>
          <AppRouterCacheProvider>
            {children}
          </AppRouterCacheProvider>
        </ClientThemeProvider>
      </body>
    </html>
  );
}
